project:
  type: website
  output-dir: ../docs

website:
  title: "<img src='images/hex.png' style='height:36px; vertical-align:middle; margin-right:2px;'> {ecosim}"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: "Apps"
        menu:
          - text: "{ecoNiche}: multispecies niche simulator"
            href: https://marine-ecologist-econiche.share.connect.posit.cloud
          - text: "{ecoDisturb}: disturbance and community structure simulator"
            href: index.qmd
          - text: "{ecoInteract}: species interactions & population dynamics simulator"
            href: index.qmd
          - text: "{ecoRestore}: optimising spatial decisionmaking for effective restoration outcomes"
            href: index.qmd
      - text: Code
        href: https://github.com/marine-ecologist/ecosim

    right:
      - icon: github
        href: https://github.com/marine-ecologist/oceans
        aria-label: GitHub

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
    toc-title: ""
    toc-location: right
